REDIS_HOST="127.0.0.1"
REDIS_PORT="6379"

SET_NAME="zxnote_token_blacklist"

CURRENT_TIMESTAMP=$(date +%s)
EXPIRATION_TIME=7200

EXPIRATION_TIMESTAMP=$(($CURRENT_TIMESTAMP - $EXPIRATION_TIME))

redis-cli -h $REDIS_HOST -p $REDIS_PORT ZREMRANGEBYSCORE $SET_NAME -inf $EXPIRATION_TIMESTAMP
